### ISSUE TITLE
Code number for "start" and "finish"

### ISSUE THREAD

**Issue by gasko** [per-magnusson/sportident-python#5]
Current implementation fetches the Code number for all splits. But not for Start and Finish.
Have tried to understand how to fetch this data from the cards (SI8 and SI9) but with no luck. 

I would love if someone could help to extract the code number from the si cards (at least for SI8 and SI9)

**Comment by per-magnusson** [comment]
I added support for reading the codes of clear, check, start and finish in sireader2.py.
The output of si_read_card.py (which did not need to change) is now something like this:

C:\>python si_read_card.py
Trying COM4
Connected to station on port COM4
Insert SI-card to be read
Number: 7123456
Type:   SI10
Data:
card_number : 7123456
start : 2023-12-03 10:10:59
start_code : 1
finish : 2023-12-03 10:38:52
finish_code : 10
check : 2023-12-03 09:59:01
check_code : 5
clear : None
clear_code : None
84 2023-12-03 10:25:40
81 2023-12-03 10:28:45
83 2023-12-03 10:35:40

The code should now also support station codes higher than 255. 
I have not done extensive testing. Please report any bugs you find.

**Comment by gasko** [comment]
Amazing. Thanks for the fast fix!
